language: generic
env:
  global:
    - IDE_VERSION=1.6.8
  matrix:
    # - EXAMPLE="AdafruitHuzzahESP8266"
    # - EXAMPLE="AdafruitHuzzahESP8266_SSL"
    - EXAMPLE="ArduinoEthernetShield" BOARD="arduino:avr:uno"
    # - EXAMPLE="ArduinoWiFi101
    # - EXAMPLE="ArduinoWiFi101_SSL
    - EXAMPLE="ArduinoWiFiShield" BOARD="arduino:avr:uno"
    # - EXAMPLE="ArduinoYun_MQTTClient"
    # - EXAMPLE="ArduinoYun_YunMQTTClient"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:sam:" ]]; then
      arduino --install-boards arduino:sam;
    fi
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd;
    fi
  - if [[ "$BOARD" =~ "Intel:arc32" ]]; then
      arduino --install-boards Intel:arc32;
    fi
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266;
      arduino --pref "boardsmanager.additional.urls=" --save-prefs;
    fi
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - arduino --verbose-build --verify --board $BOARD $PWD/examples/$EXAMPLE/$EXAMPLE.ino;
